### ISSUE TITLE
can you provide the reference papers of the project

### ISSUE THREAD

**Issue by dbdxnuliba** [CNR-STIIMA-IRAS/rosdyn#17]
can you provide the reference papers of the project

**Comment by enricovillagrossi** [comment]
Hi @dbdxnuliba,

the rosdyn_core is based on the [book](https://www.hoepli.it/libro/robot-dynamics-algorithms/9781475764376.html).
The rosdyn_identification is based on the experience acquired during the years, most of this knowledge is in the PhD [thesis](https://www.researchgate.net/publication/313423223_Robot_Dynamics_Modelling_and_Control_for_Machining_Applications), while the most relevant papers published on the topic are:
1. `E. Villagrossi, L. Simoni, M. Beschi, N. Pedrocchi, A. Marini, L. Molinari Tosatti, A. Visioli, A virtual force sensor for interaction tasks with conventional industrial robots, Mechatronics, Volume 50, 2018, Pages 78-86, ISSN 0957-4158, https://doi.org/10.1016/j.mechatronics.2018.01.016. (https://www.sciencedirect.com/science/article/pii/S0957415818300163)`

2. `N. Pedrocchi, E. Villagrossi, F. Vicentini and L. M. Tosatti, "Robot-dynamic calibration improvement by local identification," 2014 IEEE International Conference on Robotics and Automation (ICRA), 2014, pp. 5990-5997, doi: 10.1109/ICRA.2014.6907742.`

Let me know if you need further information.
Enrico

**Comment by dbdxnuliba** [comment]
thanks a lot!
