### ISSUE TITLE
 Missing dependency "configuration_msgs"

### ISSUE THREAD

**Issue by matthiashh** [CNR-STIIMA-IRAS/rosdyn#2]
We can not build the code with `melodic` because the dependency for `configuration_msgs` can not be resolved.

The rosinstall file installs `moveit_planning_helper` and that one lists `configuration_msgs` as one of it's dependencies [1].
But neither me nor rosdep can resolve that. Could it be that this package has not been published anywhere?

As a quick workaround, I recreated the few messages that were used. It can be found there: https://git.cs.lth.se/robotlab/dynamics_identification/configuration_msgs

[1] https://github.com/CNR-STIIMA-IRAS/moveit_planning_helper/blob/6773a03da1ea2bf30b834692a08be38b0785537d/CMakeLists.txt

**Comment by ManuelBeschi** [comment]
Hi,
thanks for highlighting the issue. The dependency of configuration_msgs has been removed.
